// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIlExMGC9kjb3uMhduzmBSrAkEG8NcdtI',
    appId: '1:431071771507:android:f73fe5066074a9f300a306',
    messagingSenderId: '431071771507',
    projectId: 'employee-ams',
    storageBucket: 'employee-ams.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzb4ZvKj28oK6ScAzVDZR2p9D8ckLHA0U',
    appId: '1:431071771507:ios:0b2f2aac836f33df00a306',
    messagingSenderId: '431071771507',
    projectId: 'employee-ams',
    storageBucket: 'employee-ams.appspot.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa75DiAbk3R6pxMC40HGpg7w4QcvWRSWE',
    appId: '1:431071771507:web:8af2de084875ed1400a306',
    messagingSenderId: '431071771507',
    projectId: 'employee-ams',
    authDomain: 'employee-ams.firebaseapp.com',
    storageBucket: 'employee-ams.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzb4ZvKj28oK6ScAzVDZR2p9D8ckLHA0U',
    appId: '1:431071771507:ios:0b2f2aac836f33df00a306',
    messagingSenderId: '431071771507',
    projectId: 'employee-ams',
    storageBucket: 'employee-ams.appspot.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa75DiAbk3R6pxMC40HGpg7w4QcvWRSWE',
    appId: '1:431071771507:web:fa17d954c47fd6e100a306',
    messagingSenderId: '431071771507',
    projectId: 'employee-ams',
    authDomain: 'employee-ams.firebaseapp.com',
    storageBucket: 'employee-ams.appspot.com',
  );

}